---
title: "Project-3-stacked"
author: "George Paul,"
date: "2023-03-29"
output: 
  prettydoc::html_pretty:
    theme: cayman
---

# Libraries
```{r}
library(class)
library(janitor)
library(neuralnet)
library(caret)
library(kernlab)
library(C50)
library(randomForest)
```

# Combined Data Frame
```{r}
test.labels <- read.csv("test.labels.csv")
ann.preds <- read.csv("ann.preds.csv")
tree.preds <- read.csv("decision.tree.csv")
knn.preds <- read.csv("employees.knn.csv")
logreg.preds <- read.csv("logreg.preds.csv")
rm.preds <- read.csv("rm.preds.csv")
svm.preds <- read.csv("svm.preds.csv")

combined.df <- data.frame(Attrition = test.labels[,2],
                          ann = ann.preds[,2],
                          tree = tree.preds[,2],
                          knn = knn.preds[,2],
                          logreg = logreg.preds[,2],
                          rm = rm.preds[,2],
                          svm = svm.preds[,2])

combined.df$Attrition <- as.factor(combined.df$Attrition)
combined.df$tree <- as.factor(combined.df$tree)
combined.df$rm <- as.factor(combined.df$rm)
combined.df$svm <- as.factor(combined.df$svm)

combined.df <- clean_names(combined.df)
kappa.table <- read.csv("kappa.table.csv")
kappa.table$X <- NULL
```

# New Train/Test
```{r}
n2 <- nrow(combined.df)
set.seed(0)
idx2 <- sample(n2, n2*.7)

final.train <- combined.df[idx2,]
final.test <- combined.df[-idx2,]
```

# Fit Final Models

## Random Forest
```{r}
set.seed(1)
final.rf <- randomForest(attrition ~ ., data = final.train)
final.rf.preds <- predict(final.rf, final.test)
confusionMatrix(final.rf.preds, final.test$attrition)
final.rf.kappa <- confusionMatrix(final.rf.preds, final.test$attrition)$overall[2]
```

## Boosted Decision Tree
```{r}
grid_tree <- expand.grid(.trials = c(1,5,10),
                         .model = "tree",
                         .winnow = "FALSE")
final.tree <- train(attrition ~ ., data = final.train, method = "C5.0",
           metric = "Kappa",
           trControl = ctrl,
           tuneGrid = grid_tree)
final.tree
final.tree.preds <- predict(final.tree, final.test)
confusionMatrix(final.tree.preds, final.test$attrition)
final.tree.kappa <- confusionMatrix(final.tree.preds, final.test$attrition)$overall[2]
```

# Graphs/Figures
```{r}
kappa.table[7,1] <- "Final RF"
kappa.table[7,2] <- final.rf.kappa
kappa.table[8,1] <- "Final Tree"
kappa.table[8,2] <- final.tree.kappa

barplot(kappa.table$kappa, names.arg = kappa.table$model)
```